### ISSUE TITLE
Investigate Warnings for Invalid Types in Testing

### ISSUE THREAD

**Issue by robertcrockett** [robertcrockett/memory-react#63]
In the Game.test.jsx tests, the following warnings appear:

```code 
stderr | src/components/Game.test.jsx > Renders the Game component > renders a Game
Warning: Failed prop type: Invalid prop `onCellClick` of type `boolean` supplied to `Game`, expected `function`.
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:16:21)
Warning: Failed prop type: Invalid prop `onStartClick` of type `boolean` supplied to `Game`, expected `function`.
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:16:21)
Warning: Failed prop type: Invalid prop `gameStatus` of type `boolean` supplied to `Game`, expected `string`.
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:[16](https://github.com/robertcrockett/memory-react/actions/runs/7422538516/job/20198036879#step:6:17):21)
Warning: Failed prop type: Invalid prop `onClick` of type `boolean` supplied to `Cell`, expected `function`.
    at Cell (/home/runner/work/memory-react/memory-react/src/components/Cell.jsx:10:21)
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:16:21)
Warning: Failed prop type: Invalid prop `onClick` of type `boolean` supplied to `Footer`, expected `function`.
    at Footer (/home/runner/work/memory-react/memory-react/src/components/Footer.jsx:10:23)
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:16:21)
Warning: Failed prop type: Invalid prop `gameStatus` of type `boolean` supplied to `Footer`, expected `string`.
    at Footer (/home/runner/work/memory-react/memory-react/src/components/Footer.jsx:10:23)
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:16:[21](https://github.com/robertcrockett/memory-react/actions/runs/7422538516/job/20198036879#step:6:22))
Warning: Expected `onClick` listener to be a function, instead got a value of `boolean` type.
    at button
    at div
    at Footer (/home/runner/work/memory-react/memory-react/src/components/Footer.jsx:10:23)
    at Game (/home/runner/work/memory-react/memory-react/src/components/Game.jsx:16:21)
```

**Comment by robertcrockett** [comment]
This is resolved the PR #64.
